version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

executors:
  builder:
    docker:
      - image: google/cloud-sdk

jobs:
  deploy:
    executor:
      name: builder
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/initialize
      - gcp-cli/install
      - run:
          name: Push image to GCR
          command: |
            gcloud --quiet auth configure-docker

            export IMAGE=gcr.io/${GOOGLE_PROJECT_ID}/prefect-flows:`git rev-parse --short HEAD`

            docker build -t ${IMAGE} -f ./prefect-flows/Dockerfile .
            docker push $IMAGE
            echo "export DEPLOY_IMAGE=${IMAGE}" >> $BASH_ENV
      - run:
          name: Deploy
          command: |
            cd prefect-flows
            poetry install
            poetry run prefect-util deploy --image ${DEPLOY_IMAGE} --pool demo \
              --namespace demo --config-map demo-config --env dev --app demo-flows \
              --service-account demo-flows --flow-registry prefect_flows.demo:demo_flow_group

workflows:
  deploy:
    jobs:
      - deploy
