apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"
resources:
  - ./service_account.yaml

namePrefix: demo-
commonLabels:
  agent-flow-group: demo
configMapGenerator:
  - literals:
      - WORK_POOL=demo
      - PREFECT_KUBERNETES_CLUSTER_UID=UID_HERE
    name: config
namespace: demo
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: demo
    setRoleBindingSubjects: allServiceAccounts
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true
