apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: prefect-agent
  namespace: "prefect"
  labels:
    app.kubernetes.io/name: prefect-agent
    app.kubernetes.io/instance: prefect-agent
    app.kubernetes.io/component: agent
    prefect-version: 2.7.4-python3.10
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-agent
  labels:
    app.kubernetes.io/name: prefect-agent
    helm.sh/chart: prefect-agent-2022.12.22
    app.kubernetes.io/instance: prefect-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: agent
    prefect-version: 2.7.4-python3.10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prefect-agent
subjects:
  - kind: ServiceAccount
    name: prefect-agent
    namespace: "prefect"
