apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent
subjects:
  - kind: ServiceAccount
    name: prefect-agent
